name: Release

on:
  push:
    branches: [master]


jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout [master]
        uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
